extends: airbnb-base
parser: babel-eslint
env:
  browser: true
  node: true
  jasmine: true

globals:
  atom: true
  waitsForPromise: true

settings:
  import/core-modules: [ atom ]

rules:
  no-console: [2, { allow: ["warn", "error"] }]
  no-param-reassign: [0]
  no-underscore-dangle: [0]
  no-useless-escape: [0]
  prefer-rest-params: [0]
  class-methods-use-this: [0]
