plugins:
  - prettier
  - flowtype

extends:
  - prettier
  - prettier/flowtype

parser: babel-eslint

env:
  browser: true
  node: true
  jasmine: true

globals:
  atom: true
  waitsForPromise: true

settings:
  import/core-modules: [ atom ]

rules:
  prettier/prettier:
    - error
