// Generated by CoffeeScript 1.10.0
(function() {
  var child_process, os, spawn,
    slice = [].slice;

  child_process = require('child_process');

  os = require('os');

  spawn = function(command) {
    var a, c, o, ref;
    ref = command.split(' '), c = ref[0], a = 2 <= ref.length ? slice.call(ref, 1) : [];
    o = child_process.spawnSync(c, a);
    o.stdout = o.stdout.toString().trim();
    o.stderr = o.stderr.toString().trim();
    return o;
  };

  if (!(/\ 2\./.test(spawn('python --version').stderr) || /\ 2\./.test(spawn('python2 --version').stderr))) {
    throw new Error('Python2 is required to build Hydrogen');
  }

  if (!spawn('pip show notebook').stdout) {
    throw new Error('Please install notebook with "pip install ipython[notebook]"');
  }

  if (os.platform() === 'darwin') {
    if (!spawn("brew list | grep 'pkg-config'").stdout.length) {
      throw new Error('You need pkg-config to install zmq: brew install pkg-config');
    }
    if (!spawn("brew list | grep 'zeromq'").stdout.length) {
      throw new Error('You need ZMQ to use Hydrogen: brew install zeromq');
    }
  }

}).call(this);
