// flow-typed signature: 0ab799bbbb837833bc2de1714056add4
// flow-typed version: <<STUB>>/anser_v^1.4.4/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'anser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'anser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'anser/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'anser/lib/index.js' {
  declare module.exports: $Exports<'anser/lib/index'>;
}
