// flow-typed signature: ce46f558f83e8be38b98c2ae7f228981
// flow-typed version: <<STUB>>/atom-select-list_v0.2.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom-select-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom-select-list' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom-select-list/src/select-list-view' {
  declare module.exports: any;
}

declare module 'atom-select-list/test/select-list-view.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom-select-list/src/select-list-view.js' {
  declare module.exports: $Exports<'atom-select-list/src/select-list-view'>;
}
declare module 'atom-select-list/test/select-list-view.test.js' {
  declare module.exports: $Exports<'atom-select-list/test/select-list-view.test'>;
}
