// flow-typed signature: 121f38cac3bcd4db10e53c2a1880e919
// flow-typed version: <<STUB>>/atom-space-pen-views_v^2.0.5/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom-space-pen-views'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom-space-pen-views' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom-space-pen-views/lib/main' {
  declare module.exports: any;
}

declare module 'atom-space-pen-views/lib/scroll-view' {
  declare module.exports: any;
}

declare module 'atom-space-pen-views/lib/select-list-view' {
  declare module.exports: any;
}

declare module 'atom-space-pen-views/lib/text-editor-view' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom-space-pen-views/lib/main.js' {
  declare module.exports: $Exports<'atom-space-pen-views/lib/main'>;
}
declare module 'atom-space-pen-views/lib/scroll-view.js' {
  declare module.exports: $Exports<'atom-space-pen-views/lib/scroll-view'>;
}
declare module 'atom-space-pen-views/lib/select-list-view.js' {
  declare module.exports: $Exports<'atom-space-pen-views/lib/select-list-view'>;
}
declare module 'atom-space-pen-views/lib/text-editor-view.js' {
  declare module.exports: $Exports<'atom-space-pen-views/lib/text-editor-view'>;
}
