// flow-typed signature: 8e927c65bc2290554a14fcaf0e96e886
// flow-typed version: <<STUB>>/atom-jasmine2-test-runner_v^1.0.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom-jasmine2-test-runner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom-jasmine2-test-runner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom-jasmine2-test-runner/lib/atom-reporter/atom-reporter' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/atom-reporter/expectation-view' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/atom-reporter/j2-reporter-view' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/atom-reporter/results-view' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/atom-reporter/spec-result-view' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/atom-reporter/stack-trace-view' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/atom-reporter/suite-result-view' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/atom-reporter/tabs-view' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/atom-reporter/timer-view' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/create-runner' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/spec-helper/atom' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/spec-helper/attach-to-dom' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/spec-helper/ci' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/spec-helper/clock' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/spec-helper/deprecations' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/spec-helper/fixtures' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/spec-helper/install-dep' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/spec-helper/pathwatcher' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/spec-helper/profile' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/spec-helper/set' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/spec-helper/spec-helper-view' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/spec-helper/spec-helper' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/spec-helper/yield' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/lib/time-reporter/time-reporter' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/jasmine/jasmine-spec-v1' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/jasmine/jasmine-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/reporter/reporter-spec-v1' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/reporter/reporter-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/runner' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/atom-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/attach-to-dom-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/ci-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/clock-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/deprecations-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/fixtures-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/jasmine-focused-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/jasmine-jquery-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/jasmine-json-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/jasmine-pass-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/jasmine-promises-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/jasmine-should-fail-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/jasmine-tagged-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/local-storage-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/matchers-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/pathwatcher-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/profile-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/set-spec' {
  declare module.exports: any;
}

declare module 'atom-jasmine2-test-runner/spec/spec-helper/unspy-spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom-jasmine2-test-runner/index' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner'>;
}
declare module 'atom-jasmine2-test-runner/index.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner'>;
}
declare module 'atom-jasmine2-test-runner/lib/atom-reporter/atom-reporter.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/atom-reporter/atom-reporter'>;
}
declare module 'atom-jasmine2-test-runner/lib/atom-reporter/expectation-view.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/atom-reporter/expectation-view'>;
}
declare module 'atom-jasmine2-test-runner/lib/atom-reporter/j2-reporter-view.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/atom-reporter/j2-reporter-view'>;
}
declare module 'atom-jasmine2-test-runner/lib/atom-reporter/results-view.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/atom-reporter/results-view'>;
}
declare module 'atom-jasmine2-test-runner/lib/atom-reporter/spec-result-view.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/atom-reporter/spec-result-view'>;
}
declare module 'atom-jasmine2-test-runner/lib/atom-reporter/stack-trace-view.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/atom-reporter/stack-trace-view'>;
}
declare module 'atom-jasmine2-test-runner/lib/atom-reporter/suite-result-view.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/atom-reporter/suite-result-view'>;
}
declare module 'atom-jasmine2-test-runner/lib/atom-reporter/tabs-view.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/atom-reporter/tabs-view'>;
}
declare module 'atom-jasmine2-test-runner/lib/atom-reporter/timer-view.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/atom-reporter/timer-view'>;
}
declare module 'atom-jasmine2-test-runner/lib/create-runner.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/create-runner'>;
}
declare module 'atom-jasmine2-test-runner/lib/spec-helper/atom.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/spec-helper/atom'>;
}
declare module 'atom-jasmine2-test-runner/lib/spec-helper/attach-to-dom.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/spec-helper/attach-to-dom'>;
}
declare module 'atom-jasmine2-test-runner/lib/spec-helper/ci.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/spec-helper/ci'>;
}
declare module 'atom-jasmine2-test-runner/lib/spec-helper/clock.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/spec-helper/clock'>;
}
declare module 'atom-jasmine2-test-runner/lib/spec-helper/deprecations.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/spec-helper/deprecations'>;
}
declare module 'atom-jasmine2-test-runner/lib/spec-helper/fixtures.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/spec-helper/fixtures'>;
}
declare module 'atom-jasmine2-test-runner/lib/spec-helper/install-dep.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/spec-helper/install-dep'>;
}
declare module 'atom-jasmine2-test-runner/lib/spec-helper/pathwatcher.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/spec-helper/pathwatcher'>;
}
declare module 'atom-jasmine2-test-runner/lib/spec-helper/profile.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/spec-helper/profile'>;
}
declare module 'atom-jasmine2-test-runner/lib/spec-helper/set.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/spec-helper/set'>;
}
declare module 'atom-jasmine2-test-runner/lib/spec-helper/spec-helper-view.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/spec-helper/spec-helper-view'>;
}
declare module 'atom-jasmine2-test-runner/lib/spec-helper/spec-helper.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/spec-helper/spec-helper'>;
}
declare module 'atom-jasmine2-test-runner/lib/spec-helper/yield.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/spec-helper/yield'>;
}
declare module 'atom-jasmine2-test-runner/lib/time-reporter/time-reporter.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/lib/time-reporter/time-reporter'>;
}
declare module 'atom-jasmine2-test-runner/spec/jasmine/jasmine-spec-v1.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/jasmine/jasmine-spec-v1'>;
}
declare module 'atom-jasmine2-test-runner/spec/jasmine/jasmine-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/jasmine/jasmine-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/reporter/reporter-spec-v1.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/reporter/reporter-spec-v1'>;
}
declare module 'atom-jasmine2-test-runner/spec/reporter/reporter-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/reporter/reporter-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/runner.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/runner'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/atom-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/atom-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/attach-to-dom-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/attach-to-dom-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/ci-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/ci-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/clock-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/clock-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/deprecations-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/deprecations-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/fixtures-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/fixtures-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/jasmine-focused-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/jasmine-focused-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/jasmine-jquery-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/jasmine-jquery-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/jasmine-json-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/jasmine-json-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/jasmine-pass-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/jasmine-pass-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/jasmine-promises-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/jasmine-promises-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/jasmine-should-fail-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/jasmine-should-fail-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/jasmine-tagged-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/jasmine-tagged-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/local-storage-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/local-storage-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/matchers-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/matchers-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/pathwatcher-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/pathwatcher-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/profile-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/profile-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/set-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/set-spec'>;
}
declare module 'atom-jasmine2-test-runner/spec/spec-helper/unspy-spec.js' {
  declare module.exports: $Exports<'atom-jasmine2-test-runner/spec/spec-helper/unspy-spec'>;
}
