// flow-typed signature: c0331fb4c2bf4b62ffe4c623b0254d81
// flow-typed version: <<STUB>>/atom-select-list_v^0.8.0/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom-select-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom-select-list' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom-select-list/lib/select-list-properties' {
  declare module.exports: any;
}

declare module 'atom-select-list/lib/select-list-view' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom-select-list/lib/select-list-properties.js' {
  declare module.exports: $Exports<'atom-select-list/lib/select-list-properties'>;
}
declare module 'atom-select-list/lib/select-list-view.js' {
  declare module.exports: $Exports<'atom-select-list/lib/select-list-view'>;
}
