// flow-typed signature: 88aa0c4626f0e207a735f86d58f5fe7b
// flow-typed version: <<STUB>>/escape-carriage_v^1.2.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'escape-carriage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'escape-carriage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'escape-carriage/test/benchmark' {
  declare module.exports: any;
}

declare module 'escape-carriage/test/index-spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'escape-carriage/index' {
  declare module.exports: $Exports<'escape-carriage'>;
}
declare module 'escape-carriage/index.js' {
  declare module.exports: $Exports<'escape-carriage'>;
}
declare module 'escape-carriage/test/benchmark.js' {
  declare module.exports: $Exports<'escape-carriage/test/benchmark'>;
}
declare module 'escape-carriage/test/index-spec.js' {
  declare module.exports: $Exports<'escape-carriage/test/index-spec'>;
}
