// flow-typed signature: 232e7113be01d4ebec14c9f464f70a31
// flow-typed version: <<STUB>>/husky_v^0.13.3/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'husky'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'husky' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'husky/bin/install' {
  declare module.exports: any;
}

declare module 'husky/bin/uninstall' {
  declare module.exports: any;
}

declare module 'husky/src/index' {
  declare module.exports: any;
}

declare module 'husky/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'husky/bin/install.js' {
  declare module.exports: $Exports<'husky/bin/install'>;
}
declare module 'husky/bin/uninstall.js' {
  declare module.exports: $Exports<'husky/bin/uninstall'>;
}
declare module 'husky/src/index.js' {
  declare module.exports: $Exports<'husky/src/index'>;
}
declare module 'husky/test/index.js' {
  declare module.exports: $Exports<'husky/test/index'>;
}
