// flow-typed signature: afa6830228e75da0deee5ab08e8ef861
// flow-typed version: <<STUB>>/jmp_v^1.0.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jmp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jmp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jmp/scripts/doc-publish' {
  declare module.exports: any;
}

declare module 'jmp/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jmp/index' {
  declare module.exports: $Exports<'jmp'>;
}
declare module 'jmp/index.js' {
  declare module.exports: $Exports<'jmp'>;
}
declare module 'jmp/scripts/doc-publish.js' {
  declare module.exports: $Exports<'jmp/scripts/doc-publish'>;
}
declare module 'jmp/test/index.js' {
  declare module.exports: $Exports<'jmp/test/index'>;
}
