// flow-typed signature: e5d2b2cf98ce94c6e8ee3368618d3a7c
// flow-typed version: <<STUB>>/kernelspecs_v^2.0.0/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kernelspecs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kernelspecs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kernelspecs/lib/traverse' {
  declare module.exports: any;
}

declare module 'kernelspecs/test/traverse_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kernelspecs/index' {
  declare module.exports: $Exports<'kernelspecs'>;
}
declare module 'kernelspecs/index.js' {
  declare module.exports: $Exports<'kernelspecs'>;
}
declare module 'kernelspecs/lib/traverse.js' {
  declare module.exports: $Exports<'kernelspecs/lib/traverse'>;
}
declare module 'kernelspecs/test/traverse_spec.js' {
  declare module.exports: $Exports<'kernelspecs/test/traverse_spec'>;
}
