// flow-typed signature: 9d0199fea25717d4016d5222a98421e1
// flow-typed version: <<STUB>>/loophole_v^1.1.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loophole'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'loophole' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loophole/lib/loophole' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loophole/lib/loophole.js' {
  declare module.exports: $Exports<'loophole/lib/loophole'>;
}
