// flow-typed signature: 839ddfd7863d6f5f1dab8ab03fe9ca11
// flow-typed version: <<STUB>>/markdox_v^0.1.10/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdox/examples/example' {
  declare module.exports: any;
}

declare module 'markdox/examples/fixtures/dox-parser' {
  declare module.exports: any;
}

declare module 'markdox/examples/fixtures/small-parser' {
  declare module.exports: any;
}

declare module 'markdox/examples/fixtures/tags' {
  declare module.exports: any;
}

declare module 'markdox/lib/compiler' {
  declare module.exports: any;
}

declare module 'markdox/lib/formatter' {
  declare module.exports: any;
}

declare module 'markdox/lib/markdox' {
  declare module.exports: any;
}

declare module 'markdox/test/customCompiler-test' {
  declare module.exports: any;
}

declare module 'markdox/test/customFormatter-test' {
  declare module.exports: any;
}

declare module 'markdox/test/escapeComplexTypes-test' {
  declare module.exports: any;
}

declare module 'markdox/test/file-order-test' {
  declare module.exports: any;
}

declare module 'markdox/test/fixtures/complexTypes' {
  declare module.exports: any;
}

declare module 'markdox/test/random-order-test' {
  declare module.exports: any;
}

declare module 'markdox/test/transformTitle-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdox/examples/example.js' {
  declare module.exports: $Exports<'markdox/examples/example'>;
}
declare module 'markdox/examples/fixtures/dox-parser.js' {
  declare module.exports: $Exports<'markdox/examples/fixtures/dox-parser'>;
}
declare module 'markdox/examples/fixtures/small-parser.js' {
  declare module.exports: $Exports<'markdox/examples/fixtures/small-parser'>;
}
declare module 'markdox/examples/fixtures/tags.js' {
  declare module.exports: $Exports<'markdox/examples/fixtures/tags'>;
}
declare module 'markdox/index' {
  declare module.exports: $Exports<'markdox'>;
}
declare module 'markdox/index.js' {
  declare module.exports: $Exports<'markdox'>;
}
declare module 'markdox/lib/compiler.js' {
  declare module.exports: $Exports<'markdox/lib/compiler'>;
}
declare module 'markdox/lib/formatter.js' {
  declare module.exports: $Exports<'markdox/lib/formatter'>;
}
declare module 'markdox/lib/markdox.js' {
  declare module.exports: $Exports<'markdox/lib/markdox'>;
}
declare module 'markdox/test/customCompiler-test.js' {
  declare module.exports: $Exports<'markdox/test/customCompiler-test'>;
}
declare module 'markdox/test/customFormatter-test.js' {
  declare module.exports: $Exports<'markdox/test/customFormatter-test'>;
}
declare module 'markdox/test/escapeComplexTypes-test.js' {
  declare module.exports: $Exports<'markdox/test/escapeComplexTypes-test'>;
}
declare module 'markdox/test/file-order-test.js' {
  declare module.exports: $Exports<'markdox/test/file-order-test'>;
}
declare module 'markdox/test/fixtures/complexTypes.js' {
  declare module.exports: $Exports<'markdox/test/fixtures/complexTypes'>;
}
declare module 'markdox/test/random-order-test.js' {
  declare module.exports: $Exports<'markdox/test/random-order-test'>;
}
declare module 'markdox/test/transformTitle-test.js' {
  declare module.exports: $Exports<'markdox/test/transformTitle-test'>;
}
