// flow-typed signature: 9450876c8960e4e1428458c8b5688032
// flow-typed version: <<STUB>>/mathjax-electron_v^3.0.0/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mathjax-electron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mathjax-electron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mathjax-electron/MathJax-2.7.5/config/nteract' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/FontWarnings' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/HelpDialog' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/jsMath2jax' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/MatchWebFonts' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/MathEvents' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/MathZoom' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/Safe' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/action' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/AMScd' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/AMSmath' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/AMSsymbols' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/autobold' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/autoload-all' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/bbox' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/begingroup' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/boldsymbol' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/cancel' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/color' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/enclose' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/extpfeil' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/HTML' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/mathchoice' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/mediawiki-texvc' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/mhchem' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/mhchem3/mhchem' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/newcommand' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/noErrors' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/noUndefined' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/unicode' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/verb' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/tex2jax' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/extensions/toMathML' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/jax' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/Arrows' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/BasicLatin' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/CombDiacritMarks' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/CombDiactForSymbols' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/Dingbats' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/GeneralPunctuation' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/GeometricShapes' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/GreekAndCoptic' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/Latin1Supplement' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/LetterlikeSymbols' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/MathOperators' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/MiscMathSymbolsA' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/MiscMathSymbolsB' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/MiscSymbolsAndArrows' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/MiscTechnical' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/SpacingModLetters' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/SupplementalArrowsA' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/SupplementalArrowsB' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/SuppMathOperators' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/input/TeX/config' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/input/TeX/jax' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/annotation-xml' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/maction' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/menclose' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/mglyph' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/mmultiscripts' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/ms' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/mtable' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/multiline' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/config' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/AMS-Regular' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Caligraphic-Bold' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/fontdata-extra' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/fontdata' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Fraktur-Bold' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Fraktur-Regular' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Main-Bold' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Math-BoldItalic' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/SansSerif-Bold' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/SansSerif-Italic' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/SansSerif-Regular' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Script-Regular' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Typewriter-Regular' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/jax' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/PlainSource/config' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/jax/output/PlainSource/jax' {
  declare module.exports: any;
}

declare module 'mathjax-electron/MathJax-2.7.5/MathJax' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mathjax-electron/index' {
  declare module.exports: $Exports<'mathjax-electron'>;
}
declare module 'mathjax-electron/index.js' {
  declare module.exports: $Exports<'mathjax-electron'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/config/nteract.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/config/nteract'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/FontWarnings.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/FontWarnings'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/HelpDialog.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/HelpDialog'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/jsMath2jax.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/jsMath2jax'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/MatchWebFonts.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/MatchWebFonts'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/MathEvents.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/MathEvents'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/MathZoom.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/MathZoom'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/Safe.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/Safe'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/action.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/action'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/AMScd.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/AMScd'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/AMSmath.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/AMSmath'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/AMSsymbols.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/AMSsymbols'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/autobold.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/autobold'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/autoload-all.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/autoload-all'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/bbox.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/bbox'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/begingroup.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/begingroup'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/boldsymbol.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/boldsymbol'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/cancel.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/cancel'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/color.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/color'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/enclose.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/enclose'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/extpfeil.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/extpfeil'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/HTML.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/HTML'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/mathchoice.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/mathchoice'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/mediawiki-texvc.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/mediawiki-texvc'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/mhchem.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/mhchem'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/mhchem3/mhchem.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/mhchem3/mhchem'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/newcommand.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/newcommand'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/noErrors.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/noErrors'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/noUndefined.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/noUndefined'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/unicode.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/unicode'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/TeX/verb.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/TeX/verb'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/tex2jax.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/tex2jax'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/extensions/toMathML.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/extensions/toMathML'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/jax.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/jax'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/Arrows.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/Arrows'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/BasicLatin.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/BasicLatin'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/CombDiacritMarks.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/CombDiacritMarks'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/CombDiactForSymbols.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/CombDiactForSymbols'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/Dingbats.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/Dingbats'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/GeneralPunctuation.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/GeneralPunctuation'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/GeometricShapes.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/GeometricShapes'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/GreekAndCoptic.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/GreekAndCoptic'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/Latin1Supplement.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/Latin1Supplement'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/LetterlikeSymbols.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/LetterlikeSymbols'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/MathOperators.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/MathOperators'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/MiscMathSymbolsA.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/MiscMathSymbolsA'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/MiscMathSymbolsB.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/MiscMathSymbolsB'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/MiscSymbolsAndArrows.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/MiscSymbolsAndArrows'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/MiscTechnical.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/MiscTechnical'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/SpacingModLetters.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/SpacingModLetters'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/SupplementalArrowsA.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/SupplementalArrowsA'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/SupplementalArrowsB.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/SupplementalArrowsB'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/SuppMathOperators.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/element/mml/optable/SuppMathOperators'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/input/TeX/config.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/input/TeX/config'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/input/TeX/jax.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/input/TeX/jax'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/annotation-xml.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/annotation-xml'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/maction.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/maction'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/menclose.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/menclose'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/mglyph.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/mglyph'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/mmultiscripts.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/mmultiscripts'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/ms.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/ms'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/mtable.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/mtable'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/multiline.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/autoload/multiline'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/config.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/config'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/AMS-Regular.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/AMS-Regular'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Caligraphic-Bold.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Caligraphic-Bold'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/fontdata-extra.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/fontdata-extra'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/fontdata.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/fontdata'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Fraktur-Bold.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Fraktur-Bold'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Fraktur-Regular.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Fraktur-Regular'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Main-Bold.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Main-Bold'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Math-BoldItalic.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Math-BoldItalic'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/SansSerif-Bold.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/SansSerif-Bold'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/SansSerif-Italic.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/SansSerif-Italic'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/SansSerif-Regular.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/SansSerif-Regular'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Script-Regular.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Script-Regular'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Typewriter-Regular.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/fonts/TeX/Typewriter-Regular'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/jax.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/CommonHTML/jax'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/PlainSource/config.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/PlainSource/config'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/jax/output/PlainSource/jax.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/jax/output/PlainSource/jax'>;
}
declare module 'mathjax-electron/MathJax-2.7.5/MathJax.js' {
  declare module.exports: $Exports<'mathjax-electron/MathJax-2.7.5/MathJax'>;
}
