// flow-typed signature: 4c286b8df2bb00acdf0afbc628c2295c
// flow-typed version: <<STUB>>/mobx-react_v^6.3.1/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-react/batchingForReactDom' {
  declare module.exports: any;
}

declare module 'mobx-react/batchingForReactNative' {
  declare module.exports: any;
}

declare module 'mobx-react/batchingOptOut' {
  declare module.exports: any;
}

declare module 'mobx-react/dist' {
  declare module.exports: any;
}

declare module 'mobx-react/dist/mobx-react.umd' {
  declare module.exports: any;
}

declare module 'mobx-react/dist/mobxreact.cjs.development' {
  declare module.exports: any;
}

declare module 'mobx-react/dist/mobxreact.cjs.production.min' {
  declare module.exports: any;
}

declare module 'mobx-react/dist/mobxreact.esm' {
  declare module.exports: any;
}

declare module 'mobx-react/dist/mobxreact.umd.development' {
  declare module.exports: any;
}

declare module 'mobx-react/dist/mobxreact.umd.production.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-react/batchingForReactDom.js' {
  declare module.exports: $Exports<'mobx-react/batchingForReactDom'>;
}
declare module 'mobx-react/batchingForReactNative.js' {
  declare module.exports: $Exports<'mobx-react/batchingForReactNative'>;
}
declare module 'mobx-react/batchingOptOut.js' {
  declare module.exports: $Exports<'mobx-react/batchingOptOut'>;
}
declare module 'mobx-react/dist/index' {
  declare module.exports: $Exports<'mobx-react/dist'>;
}
declare module 'mobx-react/dist/index.js' {
  declare module.exports: $Exports<'mobx-react/dist'>;
}
declare module 'mobx-react/dist/mobx-react.umd.js' {
  declare module.exports: $Exports<'mobx-react/dist/mobx-react.umd'>;
}
declare module 'mobx-react/dist/mobxreact.cjs.development.js' {
  declare module.exports: $Exports<'mobx-react/dist/mobxreact.cjs.development'>;
}
declare module 'mobx-react/dist/mobxreact.cjs.production.min.js' {
  declare module.exports: $Exports<'mobx-react/dist/mobxreact.cjs.production.min'>;
}
declare module 'mobx-react/dist/mobxreact.esm.js' {
  declare module.exports: $Exports<'mobx-react/dist/mobxreact.esm'>;
}
declare module 'mobx-react/dist/mobxreact.umd.development.js' {
  declare module.exports: $Exports<'mobx-react/dist/mobxreact.umd.development'>;
}
declare module 'mobx-react/dist/mobxreact.umd.production.min.js' {
  declare module.exports: $Exports<'mobx-react/dist/mobxreact.umd.production.min'>;
}
