// flow-typed signature: b268be41d79e2db1b88fbfc6efd8d5f0
// flow-typed version: <<STUB>>/react-rangeslider_v^2.1.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-rangeslider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-rangeslider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-rangeslider/lib/index' {
  declare module.exports: any;
}

declare module 'react-rangeslider/lib/Rangeslider' {
  declare module.exports: any;
}

declare module 'react-rangeslider/lib/utils' {
  declare module.exports: any;
}

declare module 'react-rangeslider/umd/rangeslider' {
  declare module.exports: any;
}

declare module 'react-rangeslider/umd/rangeslider.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-rangeslider/lib/index.js' {
  declare module.exports: $Exports<'react-rangeslider/lib/index'>;
}
declare module 'react-rangeslider/lib/Rangeslider.js' {
  declare module.exports: $Exports<'react-rangeslider/lib/Rangeslider'>;
}
declare module 'react-rangeslider/lib/utils.js' {
  declare module.exports: $Exports<'react-rangeslider/lib/utils'>;
}
declare module 'react-rangeslider/umd/rangeslider.js' {
  declare module.exports: $Exports<'react-rangeslider/umd/rangeslider'>;
}
declare module 'react-rangeslider/umd/rangeslider.min.js' {
  declare module.exports: $Exports<'react-rangeslider/umd/rangeslider.min'>;
}
