// flow-typed signature: 3cfdafd6096ff87ff7cc05f511ee3eaf
// flow-typed version: <<STUB>>/tildify_v^1.2.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tildify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tildify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'tildify/index' {
  declare module.exports: $Exports<'tildify'>;
}
declare module 'tildify/index.js' {
  declare module.exports: $Exports<'tildify'>;
}
