// flow-typed signature: f02bea613215ebc34510994a620e0d36
// flow-typed version: <<STUB>>/transformime_v^3.2.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'transformime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module "transformime" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "transformime/dist/transformime" {
  declare module.exports: any;
}

declare module "transformime/lib/commonmark.transform" {
  declare module.exports: any;
}

declare module "transformime/lib/html.transform" {
  declare module.exports: any;
}

declare module "transformime/lib/image.transform" {
  declare module.exports: any;
}

declare module "transformime/lib/latex.transform" {
  declare module.exports: any;
}

declare module "transformime/lib/pdf.transform" {
  declare module.exports: any;
}

declare module "transformime/lib/script.transform" {
  declare module.exports: any;
}

declare module "transformime/lib/svg.transform" {
  declare module.exports: any;
}

declare module "transformime/lib/text.transform" {
  declare module.exports: any;
}

declare module "transformime/lib/transformime" {
  declare module.exports: any;
}

declare module "transformime/src/commonmark.transform" {
  declare module.exports: any;
}

declare module "transformime/src/html.transform" {
  declare module.exports: any;
}

declare module "transformime/src/image.transform" {
  declare module.exports: any;
}

declare module "transformime/src/latex.transform" {
  declare module.exports: any;
}

declare module "transformime/src/pdf.transform" {
  declare module.exports: any;
}

declare module "transformime/src/script.transform" {
  declare module.exports: any;
}

declare module "transformime/src/svg.transform" {
  declare module.exports: any;
}

declare module "transformime/src/text.transform" {
  declare module.exports: any;
}

declare module "transformime/src/transformime" {
  declare module.exports: any;
}

declare module "transformime/test/commonmark.transform.test" {
  declare module.exports: any;
}

declare module "transformime/test/html.transform.test" {
  declare module.exports: any;
}

declare module "transformime/test/image.transform.test" {
  declare module.exports: any;
}

declare module "transformime/test/karma.conf" {
  declare module.exports: any;
}

declare module "transformime/test/latex.transform.test" {
  declare module.exports: any;
}

declare module "transformime/test/pdf.transform.test" {
  declare module.exports: any;
}

declare module "transformime/test/script.transform.test" {
  declare module.exports: any;
}

declare module "transformime/test/svg.transform.test" {
  declare module.exports: any;
}

declare module "transformime/test/text.transform.test" {
  declare module.exports: any;
}

declare module "transformime/test/transformime.test" {
  declare module.exports: any;
}

// Filename aliases
declare module "transformime/dist/transformime.js" {
  declare module.exports: $Exports<"transformime/dist/transformime">;
}
declare module "transformime/lib/commonmark.transform.js" {
  declare module.exports: $Exports<"transformime/lib/commonmark.transform">;
}
declare module "transformime/lib/html.transform.js" {
  declare module.exports: $Exports<"transformime/lib/html.transform">;
}
declare module "transformime/lib/image.transform.js" {
  declare module.exports: $Exports<"transformime/lib/image.transform">;
}
declare module "transformime/lib/latex.transform.js" {
  declare module.exports: $Exports<"transformime/lib/latex.transform">;
}
declare module "transformime/lib/pdf.transform.js" {
  declare module.exports: $Exports<"transformime/lib/pdf.transform">;
}
declare module "transformime/lib/script.transform.js" {
  declare module.exports: $Exports<"transformime/lib/script.transform">;
}
declare module "transformime/lib/svg.transform.js" {
  declare module.exports: $Exports<"transformime/lib/svg.transform">;
}
declare module "transformime/lib/text.transform.js" {
  declare module.exports: $Exports<"transformime/lib/text.transform">;
}
declare module "transformime/lib/transformime.js" {
  declare module.exports: $Exports<"transformime/lib/transformime">;
}
declare module "transformime/src/commonmark.transform.js" {
  declare module.exports: $Exports<"transformime/src/commonmark.transform">;
}
declare module "transformime/src/html.transform.js" {
  declare module.exports: $Exports<"transformime/src/html.transform">;
}
declare module "transformime/src/image.transform.js" {
  declare module.exports: $Exports<"transformime/src/image.transform">;
}
declare module "transformime/src/latex.transform.js" {
  declare module.exports: $Exports<"transformime/src/latex.transform">;
}
declare module "transformime/src/pdf.transform.js" {
  declare module.exports: $Exports<"transformime/src/pdf.transform">;
}
declare module "transformime/src/script.transform.js" {
  declare module.exports: $Exports<"transformime/src/script.transform">;
}
declare module "transformime/src/svg.transform.js" {
  declare module.exports: $Exports<"transformime/src/svg.transform">;
}
declare module "transformime/src/text.transform.js" {
  declare module.exports: $Exports<"transformime/src/text.transform">;
}
declare module "transformime/src/transformime.js" {
  declare module.exports: $Exports<"transformime/src/transformime">;
}
declare module "transformime/test/commonmark.transform.test.js" {
  declare module.exports: $Exports<"transformime/test/commonmark.transform.test">;
}
declare module "transformime/test/html.transform.test.js" {
  declare module.exports: $Exports<"transformime/test/html.transform.test">;
}
declare module "transformime/test/image.transform.test.js" {
  declare module.exports: $Exports<"transformime/test/image.transform.test">;
}
declare module "transformime/test/karma.conf.js" {
  declare module.exports: $Exports<"transformime/test/karma.conf">;
}
declare module "transformime/test/latex.transform.test.js" {
  declare module.exports: $Exports<"transformime/test/latex.transform.test">;
}
declare module "transformime/test/pdf.transform.test.js" {
  declare module.exports: $Exports<"transformime/test/pdf.transform.test">;
}
declare module "transformime/test/script.transform.test.js" {
  declare module.exports: $Exports<"transformime/test/script.transform.test">;
}
declare module "transformime/test/svg.transform.test.js" {
  declare module.exports: $Exports<"transformime/test/svg.transform.test">;
}
declare module "transformime/test/text.transform.test.js" {
  declare module.exports: $Exports<"transformime/test/text.transform.test">;
}
declare module "transformime/test/transformime.test.js" {
  declare module.exports: $Exports<"transformime/test/transformime.test">;
}
