// flow-typed signature: b1d8348691b66cd2a55a1075321b0db1
// flow-typed version: <<STUB>>/xmlhttprequest_v^1.8.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xmlhttprequest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xmlhttprequest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xmlhttprequest/lib/XMLHttpRequest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xmlhttprequest/lib/XMLHttpRequest.js' {
  declare module.exports: $Exports<'xmlhttprequest/lib/XMLHttpRequest'>;
}
