// flow-typed signature: bd2b1553e514b9f8ff82dda20864f402
// flow-typed version: <<STUB>>/@jupyterlab/services_v^0.42.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jupyterlab/services'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jupyterlab/services' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jupyterlab/services/lib/config/index' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/contents/index' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/contents/validate' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/index' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/kernel/comm' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/kernel/default' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/kernel/future' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/kernel/index' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/kernel/kernel' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/kernel/manager' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/kernel/messages' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/kernel/serialize' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/kernel/validate' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/manager' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/session/default' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/session/index' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/session/manager' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/session/session' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/session/validate' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/terminal/default' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/terminal/index' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/terminal/manager' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/terminal/terminal' {
  declare module.exports: any;
}

declare module '@jupyterlab/services/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jupyterlab/services/lib/config/index.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/config/index'>;
}
declare module '@jupyterlab/services/lib/contents/index.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/contents/index'>;
}
declare module '@jupyterlab/services/lib/contents/validate.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/contents/validate'>;
}
declare module '@jupyterlab/services/lib/index.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/index'>;
}
declare module '@jupyterlab/services/lib/kernel/comm.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/kernel/comm'>;
}
declare module '@jupyterlab/services/lib/kernel/default.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/kernel/default'>;
}
declare module '@jupyterlab/services/lib/kernel/future.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/kernel/future'>;
}
declare module '@jupyterlab/services/lib/kernel/index.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/kernel/index'>;
}
declare module '@jupyterlab/services/lib/kernel/kernel.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/kernel/kernel'>;
}
declare module '@jupyterlab/services/lib/kernel/manager.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/kernel/manager'>;
}
declare module '@jupyterlab/services/lib/kernel/messages.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/kernel/messages'>;
}
declare module '@jupyterlab/services/lib/kernel/serialize.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/kernel/serialize'>;
}
declare module '@jupyterlab/services/lib/kernel/validate.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/kernel/validate'>;
}
declare module '@jupyterlab/services/lib/manager.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/manager'>;
}
declare module '@jupyterlab/services/lib/session/default.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/session/default'>;
}
declare module '@jupyterlab/services/lib/session/index.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/session/index'>;
}
declare module '@jupyterlab/services/lib/session/manager.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/session/manager'>;
}
declare module '@jupyterlab/services/lib/session/session.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/session/session'>;
}
declare module '@jupyterlab/services/lib/session/validate.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/session/validate'>;
}
declare module '@jupyterlab/services/lib/terminal/default.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/terminal/default'>;
}
declare module '@jupyterlab/services/lib/terminal/index.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/terminal/index'>;
}
declare module '@jupyterlab/services/lib/terminal/manager.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/terminal/manager'>;
}
declare module '@jupyterlab/services/lib/terminal/terminal.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/terminal/terminal'>;
}
declare module '@jupyterlab/services/lib/utils.js' {
  declare module.exports: $Exports<'@jupyterlab/services/lib/utils'>;
}
