// flow-typed signature: 2e424ef6c471d24021371058b7341afa
// flow-typed version: <<STUB>>/@nteract/commutable_v^7.4.3/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nteract/commutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nteract/commutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nteract/commutable/lib/cells' {
  declare module.exports: any;
}

declare module '@nteract/commutable/lib' {
  declare module.exports: any;
}

declare module '@nteract/commutable/lib/notebook' {
  declare module.exports: any;
}

declare module '@nteract/commutable/lib/outputs' {
  declare module.exports: any;
}

declare module '@nteract/commutable/lib/primitives' {
  declare module.exports: any;
}

declare module '@nteract/commutable/lib/structures' {
  declare module.exports: any;
}

declare module '@nteract/commutable/lib/v3' {
  declare module.exports: any;
}

declare module '@nteract/commutable/lib/v4' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nteract/commutable/lib/cells.js' {
  declare module.exports: $Exports<'@nteract/commutable/lib/cells'>;
}
declare module '@nteract/commutable/lib/index' {
  declare module.exports: $Exports<'@nteract/commutable/lib'>;
}
declare module '@nteract/commutable/lib/index.js' {
  declare module.exports: $Exports<'@nteract/commutable/lib'>;
}
declare module '@nteract/commutable/lib/notebook.js' {
  declare module.exports: $Exports<'@nteract/commutable/lib/notebook'>;
}
declare module '@nteract/commutable/lib/outputs.js' {
  declare module.exports: $Exports<'@nteract/commutable/lib/outputs'>;
}
declare module '@nteract/commutable/lib/primitives.js' {
  declare module.exports: $Exports<'@nteract/commutable/lib/primitives'>;
}
declare module '@nteract/commutable/lib/structures.js' {
  declare module.exports: $Exports<'@nteract/commutable/lib/structures'>;
}
declare module '@nteract/commutable/lib/v3.js' {
  declare module.exports: $Exports<'@nteract/commutable/lib/v3'>;
}
declare module '@nteract/commutable/lib/v4.js' {
  declare module.exports: $Exports<'@nteract/commutable/lib/v4'>;
}
