// flow-typed signature: 5868810f60fc7cce08b597592fa2f552
// flow-typed version: <<STUB>>/@nteract/markdown_v^4.6.1/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nteract/markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nteract/markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nteract/markdown/lib/attachment/attachment-transformer' {
  declare module.exports: any;
}

declare module '@nteract/markdown/lib' {
  declare module.exports: any;
}

declare module '@nteract/markdown/lib/markdown-previewer' {
  declare module.exports: any;
}

declare module '@nteract/markdown/lib/markdown-render' {
  declare module.exports: any;
}

declare module '@nteract/markdown/lib/remark-math/block' {
  declare module.exports: any;
}

declare module '@nteract/markdown/lib/remark-math' {
  declare module.exports: any;
}

declare module '@nteract/markdown/lib/remark-math/inline' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nteract/markdown/lib/attachment/attachment-transformer.js' {
  declare module.exports: $Exports<'@nteract/markdown/lib/attachment/attachment-transformer'>;
}
declare module '@nteract/markdown/lib/index' {
  declare module.exports: $Exports<'@nteract/markdown/lib'>;
}
declare module '@nteract/markdown/lib/index.js' {
  declare module.exports: $Exports<'@nteract/markdown/lib'>;
}
declare module '@nteract/markdown/lib/markdown-previewer.js' {
  declare module.exports: $Exports<'@nteract/markdown/lib/markdown-previewer'>;
}
declare module '@nteract/markdown/lib/markdown-render.js' {
  declare module.exports: $Exports<'@nteract/markdown/lib/markdown-render'>;
}
declare module '@nteract/markdown/lib/remark-math/block.js' {
  declare module.exports: $Exports<'@nteract/markdown/lib/remark-math/block'>;
}
declare module '@nteract/markdown/lib/remark-math/index' {
  declare module.exports: $Exports<'@nteract/markdown/lib/remark-math'>;
}
declare module '@nteract/markdown/lib/remark-math/index.js' {
  declare module.exports: $Exports<'@nteract/markdown/lib/remark-math'>;
}
declare module '@nteract/markdown/lib/remark-math/inline.js' {
  declare module.exports: $Exports<'@nteract/markdown/lib/remark-math/inline'>;
}
