// flow-typed signature: afe8e0955d87329b5d864fc99a02fd11
// flow-typed version: <<STUB>>/@nteract/mathjax_v^4.0.15/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nteract/mathjax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nteract/mathjax' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nteract/mathjax/jest.config' {
  declare module.exports: any;
}

declare module '@nteract/mathjax/lib/context' {
  declare module.exports: any;
}

declare module '@nteract/mathjax/lib' {
  declare module.exports: any;
}

declare module '@nteract/mathjax/lib/node' {
  declare module.exports: any;
}

declare module '@nteract/mathjax/lib/provider' {
  declare module.exports: any;
}

declare module '@nteract/mathjax/lib/text' {
  declare module.exports: any;
}

declare module '@nteract/mathjax/test-setup' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nteract/mathjax/jest.config.js' {
  declare module.exports: $Exports<'@nteract/mathjax/jest.config'>;
}
declare module '@nteract/mathjax/lib/context.js' {
  declare module.exports: $Exports<'@nteract/mathjax/lib/context'>;
}
declare module '@nteract/mathjax/lib/index' {
  declare module.exports: $Exports<'@nteract/mathjax/lib'>;
}
declare module '@nteract/mathjax/lib/index.js' {
  declare module.exports: $Exports<'@nteract/mathjax/lib'>;
}
declare module '@nteract/mathjax/lib/node.js' {
  declare module.exports: $Exports<'@nteract/mathjax/lib/node'>;
}
declare module '@nteract/mathjax/lib/provider.js' {
  declare module.exports: $Exports<'@nteract/mathjax/lib/provider'>;
}
declare module '@nteract/mathjax/lib/text.js' {
  declare module.exports: $Exports<'@nteract/mathjax/lib/text'>;
}
declare module '@nteract/mathjax/test-setup.js' {
  declare module.exports: $Exports<'@nteract/mathjax/test-setup'>;
}
