// flow-typed signature: 486668d903014f85753412f094a0a295
// flow-typed version: <<STUB>>/@nteract/outputs_v^3.0.11/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nteract/outputs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nteract/outputs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nteract/outputs/lib/components/display-data' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/execute-result' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/kernel-output-error' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/media/html' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/media/image' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/media' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/media/javascript' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/media/json' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/media/latex' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/media/markdown' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/media/plain' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/media/svg' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/output' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/outputStyle' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/prompt' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/rich-media' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib/components/stream-text' {
  declare module.exports: any;
}

declare module '@nteract/outputs/lib' {
  declare module.exports: any;
}

declare module '@nteract/outputs/sampleData/sampleImage' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nteract/outputs/lib/components/display-data.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/display-data'>;
}
declare module '@nteract/outputs/lib/components/execute-result.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/execute-result'>;
}
declare module '@nteract/outputs/lib/components/kernel-output-error.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/kernel-output-error'>;
}
declare module '@nteract/outputs/lib/components/media/html.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/media/html'>;
}
declare module '@nteract/outputs/lib/components/media/image.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/media/image'>;
}
declare module '@nteract/outputs/lib/components/media/index' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/media'>;
}
declare module '@nteract/outputs/lib/components/media/index.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/media'>;
}
declare module '@nteract/outputs/lib/components/media/javascript.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/media/javascript'>;
}
declare module '@nteract/outputs/lib/components/media/json.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/media/json'>;
}
declare module '@nteract/outputs/lib/components/media/latex.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/media/latex'>;
}
declare module '@nteract/outputs/lib/components/media/markdown.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/media/markdown'>;
}
declare module '@nteract/outputs/lib/components/media/plain.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/media/plain'>;
}
declare module '@nteract/outputs/lib/components/media/svg.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/media/svg'>;
}
declare module '@nteract/outputs/lib/components/output.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/output'>;
}
declare module '@nteract/outputs/lib/components/outputStyle.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/outputStyle'>;
}
declare module '@nteract/outputs/lib/components/prompt.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/prompt'>;
}
declare module '@nteract/outputs/lib/components/rich-media.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/rich-media'>;
}
declare module '@nteract/outputs/lib/components/stream-text.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib/components/stream-text'>;
}
declare module '@nteract/outputs/lib/index' {
  declare module.exports: $Exports<'@nteract/outputs/lib'>;
}
declare module '@nteract/outputs/lib/index.js' {
  declare module.exports: $Exports<'@nteract/outputs/lib'>;
}
declare module '@nteract/outputs/sampleData/sampleImage.js' {
  declare module.exports: $Exports<'@nteract/outputs/sampleData/sampleImage'>;
}
