// flow-typed signature: a8615bf6d2ea6f6628981cfdb28a9540
// flow-typed version: <<STUB>>/@nteract/transform-vega_v^7.0.10/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nteract/transform-vega'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nteract/transform-vega' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nteract/transform-vega/lib/external' {
  declare module.exports: any;
}

declare module '@nteract/transform-vega/lib' {
  declare module.exports: any;
}

declare module '@nteract/transform-vega/lib/mime' {
  declare module.exports: any;
}

declare module '@nteract/transform-vega/lib/react' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nteract/transform-vega/lib/external.js' {
  declare module.exports: $Exports<'@nteract/transform-vega/lib/external'>;
}
declare module '@nteract/transform-vega/lib/index' {
  declare module.exports: $Exports<'@nteract/transform-vega/lib'>;
}
declare module '@nteract/transform-vega/lib/index.js' {
  declare module.exports: $Exports<'@nteract/transform-vega/lib'>;
}
declare module '@nteract/transform-vega/lib/mime.js' {
  declare module.exports: $Exports<'@nteract/transform-vega/lib/mime'>;
}
declare module '@nteract/transform-vega/lib/react.js' {
  declare module.exports: $Exports<'@nteract/transform-vega/lib/react'>;
}
