module.exports =
    autocomplete:
        title: "Enable Autocomplete"
        type: 'boolean'
        default: true
    grammarToKernel:
        description: 'JSON mappings between specific kernel and a
                      language/grammar. This value is updated automatically
                      by the "switch kernel" command. If you switch from
                      python2 to python3, python3 will be used the next time
                      you open a Python file. You probably shouldn\'t
                      change this by hand.'
        type: 'string'
        default: '{}'
    kernelspec:
        title: "Kernel Spec"
        description: 'This field is autogenerated on every launch in up-to-date
            environments, also you can regenerate this with
            `hydrogen:update-kernels` command. Kernel specs as reported by
            `jupyter kernelspecs list --json` or
            `ipython kernelspecs list --json`. If these commands fail in your
            environment, you can use this field to specify your kernels, like:
            ```
            {
              "kernelspecs": {
                "ijavascript": {
                  "spec": {
                    "display_name": "IJavascript",
                    "env": {},
                    "argv": [
                      "node",
                      "/home/user/node_modules/ijavascript/lib/kernel.js",
                      "--protocol=5.0",
                      "{connection_file}"
                    ],
                    "language": "javascript"
                  },
                  "resources_dir": "/home/user/node_modules/ijavascript/images"
                }
              }
            }
            ```'
        type: 'string'
        default: '{}'
    languageMappings:
        title: "Language Mappings"
        description: 'Some packages may change the name of the grammar for
                      a language (e.g. "Python" -> "Python Django"). That
                      leaves Hydrogen unable to figure out what kernel to
                      use for your code.

                      This field should be valid JSON mapping a nonstandard
                      language name to a standard one, e.g.

                      ```{"Python Django": "python", "Ruby (Rails)": "ruby"}```'
        type: 'string'
        default: '{}'
    startupCode:
        title: "Startup Code"
        description: 'This code will be executed on kernel startup.
            Format: `{"kernel": "your code \\nmore code"}`.
            Example: `{"Python 2": "%matplotlib inline"}`'
        type: 'string'
        default: '{}'
    kernelNotifications:
        title: "Enable kernel notifications"
        description: 'By default, kernel notifications are only displayed in the
            developer console. This setting defines a RegExp to filter what
            kernel notifications will also be shown as Atom notification
            bubbles. Example: `error|warning`'
        type: 'string'
        default: '(?!)'
